### ISSUE TITLE
usage of test_infer.py

### ISSUE THREAD

**Issue by rohit9650** [mvcisback/yasit#22]
Hi,
I build the code on ubuntu-18.04 with python-3.6.9.
To understand the yasit's API, I ran the test_infer.py (by calling test_lattice_inference()), It's throwing the error:

rohit@rohit:~/ -ROHIT/yasit/build/lib/yasit$ python3 test_infer.py 
Traceback (most recent call last):
  File "/usr/lib/python3.6/pickle.py", line 269, in _getattribute
    obj = getattr(obj, subpath)
AttributeError: module 'builtins' has no attribute 'DumbSpecAttributes'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.6/pickle.py", line 918, in save_global
    obj2, parent = _getattribute(module, name)
  File "/usr/lib/python3.6/pickle.py", line 272, in _getattribute
    .format(name, obj))
AttributeError: Can't get attribute 'DumbSpecAttributes' on <module 'builtins' (built-in)>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "test_infer.py", line 129, in <module>
    test_lattice_inference()
  File "test_infer.py", line 125, in test_lattice_inference
    spec = lattice.infer(CC1, DEMOS).data
  File "/usr/local/lib/python3.6/dist-packages/yasit-0.0.0-py3.6.egg/yasit/lattice.py", line 46, in infer
    candidates = list(traverse(concept_class, demos))
  File "/usr/local/lib/python3.6/dist-packages/yasit-0.0.0-py3.6.egg/yasit/lattice.py", line 27, in traverse
    concept_class = create_lattice(concept_class).reverse()
  File "/usr/local/lib/python3.6/dist-packages/yasit-0.0.0-py3.6.egg/yasit/lattice.py", line 11, in create_lattice
    child_map = adj_list(concept_class)
  File "/usr/local/lib/python3.6/dist-packages/yasit-0.0.0-py3.6.egg/yasit/edges.py", line 28, in adj_list
    edge_generator = fn.cat(mapper(get_edges, possible_edges(concept_class)))
  File "/home/rohit/.local/lib/python3.6/site-packages/pathos/multiprocessing.py", line 137, in map
    return _pool.map(star(f), zip(*args)) # chunksize
  File "/home/rohit/.local/lib/python3.6/site-packages/multiprocess/pool.py", line 266, in map
    return self._map_async(func, iterable, mapstar, chunksize).get()
  File "/home/rohit/.local/lib/python3.6/site-packages/multiprocess/pool.py", line 644, in get
    raise self._value
  File "/home/rohit/.local/lib/python3.6/site-packages/multiprocess/pool.py", line 424, in _handle_tasks
    put(task)
  File "/home/rohit/.local/lib/python3.6/site-packages/multiprocess/connection.py", line 209, in send
    self._send_bytes(_ForkingPickler.dumps(obj))
  File "/home/rohit/.local/lib/python3.6/site-packages/multiprocess/reduction.py", line 54, in dumps
    cls(buf, protocol, *args, **kwds).dump(obj)
  File "/home/rohit/.local/lib/python3.6/site-packages/dill/_dill.py", line 454, in dump
    StockPickler.dump(self, obj)
  File "/usr/lib/python3.6/pickle.py", line 409, in dump
    self.save(obj)
  File "/usr/lib/python3.6/pickle.py", line 476, in save
    f(self, obj) # Call unbound method with explicit self
  File "/usr/lib/python3.6/pickle.py", line 751, in save_tuple
    save(element)
  File "/usr/lib/python3.6/pickle.py", line 476, in save
    f(self, obj) # Call unbound method with explicit self
  File "/usr/lib/python3.6/pickle.py", line 736, in save_tuple
    save(element)
  File "/usr/lib/python3.6/pickle.py", line 476, in save
    f(self, obj) # Call unbound method with explicit self
  File "/usr/lib/python3.6/pickle.py", line 736, in save_tuple
    save(element)
  File "/usr/lib/python3.6/pickle.py", line 476, in save
    f(self, obj) # Call unbound method with explicit self
  File "/usr/lib/python3.6/pickle.py", line 736, in save_tuple
    save(element)
  File "/usr/lib/python3.6/pickle.py", line 476, in save
    f(self, obj) # Call unbound method with explicit self
  File "/usr/lib/python3.6/pickle.py", line 736, in save_tuple
    save(element)
  File "/usr/lib/python3.6/pickle.py", line 476, in save
    f(self, obj) # Call unbound method with explicit self
  File "/usr/lib/python3.6/pickle.py", line 736, in save_tuple
    save(element)
  File "/usr/lib/python3.6/pickle.py", line 521, in save
    self.save_reduce(obj=obj, *rv)
  File "/usr/lib/python3.6/pickle.py", line 605, in save_reduce
    save(cls)
  File "/usr/lib/python3.6/pickle.py", line 476, in save
    f(self, obj) # Call unbound method with explicit self
  File "/home/rohit/.local/lib/python3.6/site-packages/dill/_dill.py", line 1374, in save_type
    obj.__bases__, _dict), obj=obj)
  File "/usr/lib/python3.6/pickle.py", line 610, in save_reduce
    save(args)
  File "/usr/lib/python3.6/pickle.py", line 476, in save
    f(self, obj) # Call unbound method with explicit self
  File "/usr/lib/python3.6/pickle.py", line 751, in save_tuple
    save(element)
  File "/usr/lib/python3.6/pickle.py", line 476, in save
    f(self, obj) # Call unbound method with explicit self
  File "/home/rohit/.local/lib/python3.6/site-packages/dill/_dill.py", line 941, in save_module_dict
    StockPickler.save_dict(pickler, obj)
  File "/usr/lib/python3.6/pickle.py", line 821, in save_dict
    self._batch_setitems(obj.items())
  File "/usr/lib/python3.6/pickle.py", line 847, in _batch_setitems
    save(v)
  File "/usr/lib/python3.6/pickle.py", line 521, in save
    self.save_reduce(obj=obj, *rv)
  File "/usr/lib/python3.6/pickle.py", line 605, in save_reduce
    save(cls)
  File "/usr/lib/python3.6/pickle.py", line 476, in save
    f(self, obj) # Call unbound method with explicit self
  File "/home/rohit/.local/lib/python3.6/site-packages/dill/_dill.py", line 1390, in save_type
    StockPickler.save_global(pickler, obj, name=name)
  File "/usr/lib/python3.6/pickle.py", line 922, in save_global
    (obj, module_name, name))
_pickle.PicklingError: Can't pickle <class 'DumbSpecAttributes'>: it's not found as builtins.DumbSpecAttributes

**Comment by mvcisback** [comment]
@rohit9650 Did you install the dependencies in `requirements.txt`?

Also I typically run the tests using `pytest`

**Comment by rohit9650** [comment]
I wasn't running the test_infer using pytest (my bad).
Now, I'm able to pass all the test.
Thanks.
